name: Run Mabl Tests

on:
  push:
    branches: [main]  # You can change this to your desired branch
  pull_request:

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Mabl CLI
      run: curl -sL https://app.mabl.com/install.sh | bash

    - name: Run Mabl Tests
      run: |
        mabl tests run \
          --api-key ${{ secrets.MABL_API_KEY }} \
          --application-id YOUR_APP_ID \
          --environment-id YOUR_ENV_ID
