name: Run Mabl Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Mabl CLI
      run: |
        curl -fsSL https://downloads.mabl.com/cli/mabl-cli-latest-linux.tar.gz -o mabl-cli.tar.gz
        mkdir mabl-cli
        tar -xzf mabl-cli.tar.gz -C mabl-cli
        sudo mv mabl-cli/mabl /usr/local/bin/

    - name: Run Mabl Tests
      run: |
        mabl tests run \
          --api-key ${{ secrets.MABL_API_KEY }} \
          --application-id IPQENisJNEutPllfOwG5DA-a\
          --environment-id QrhJzHq6UlThFhhPYqJhhA-e
